### ISSUE TITLE
example.py does not work

### ISSUE THREAD

**Issue by kevingerman** [toumorokoshi/nlgen#1]
There are several places in the example that reflect an older version of the project.   In addition to just fixing the example so that it works, it would be good to rewrite it as an acceptance test that can be executed from setup.py in the test clause.

**Comment by toumorokoshi** [comment]
Oops, sorry about that. nlgen is in a very premature alpha phase right now, and there's a lot of changes I haven't published anywhere yet.

I've got some documentation I'm finishing up for the current version. I'll link it here as well, when I'm somewhere I can finish it up. Expect something tonight or tomorrow.

Unit tests do exist for the current version of nlgen (probably the best resource for correctness), but I'll see if setup.py can't run them as well.

https://github.com/toumorokoshi/nlgen/tree/master/nlgen/tests/cfg

**Comment by toumorokoshi** [comment]
@ludyte here's the documentation I was referring to (at least for the markup interface):

http://nlgen.readthedocs.io/en/latest/cfg_tutorial.html#final-example

unit tests are still the best way to learn how to work with the api directly:

https://github.com/toumorokoshi/nlgen/blob/master/nlgen/tests/cfg/test_full.py#L4

I've published a new version, 0.0.6, which reflects these changes.

Hope that helps! If you do use nlgen, don't hesitate to give feedback or contribute: I still don't feel I have enough information to put the foot down on the best interface for this tooling, and feedback is awesome.
